from pathlib import Path

TILE_SIZE = 16
CHUNK_LOAD_RADIUS = 7
FPS = 60
CHUNK_SIZE = 32
WORLD_CHUNK_WIDTH = 64
WORLD_CHUNK_HEIGHT = 32
DIR_ROOT = str(Path(__file__).resolve().parent)

CHUNK_PX = CHUNK_SIZE * TILE_SIZE
WORLD_W_PX = WORLD_CHUNK_WIDTH * CHUNK_PX
WORLD_H_PX = WORLD_CHUNK_HEIGHT * CHUNK_PX

MAX_ENTITIES = 200
ACC_G = TILE_SIZE * 10.0  # gravity acceleration in pixels/s^2
PICKUP_RADIUS = TILE_SIZE * 5.0
PICKUP_COLLECT_RADIUS = TILE_SIZE * 1.0
PICKUP_LERP = 0.1
DIG_BASE_TIME = 0.25

HEALTH_BAR_SIZE = (100, 10)
HEALTH_BAR_POS = (10, 10)

# Core world/physics configuration values used across modules.
PICKUP_RADIUS = TILE_SIZE * 5
